apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
  replicas: 20
  selector:
    matchLabels:
      app: api
  template: 
    metadata:  
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"              
      labels:
        app: api
    spec:            
      containers:
      - name: api        
        image: fabricioveronez/api-produto
        ports:
        - containerPort: 8080        
        env:
          - name: MONGODB_URI
            value: mongodb://mongodbuser:mongodbpwd@mongo-service:27017/admin
